### ISSUE TITLE
Get a UX review

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#27]
As part of a more rigorous review process for landing shield studies (currently modeled after [this](http://webextensions-experiments.readthedocs.io/en/latest/uplifting.html#landing-in-firefox)), this study should receive a UX review.

This is a meta-issue for any UX-related concerns.

UX reviewer: jsavory

**Comment by biancadanforth** [comment]
### Initial UX Review

@biancadanforth action items:
- [ ] On the new tab page, pageAction panel and pageAction badge, ensure units of time are meaningful. See #45 .
- [ ] Make the shield icon in the pageAction white and add more left and right padding in between the badge/icon and green area. Update the shield icon color accordingly elsewhere per mocks.
- [ ] On "fast" branch, if a page has 0 blocked resources, make sure the pageAction badge and panel set timeSaved to 0 as well (they are currently decoupled).

@jsavory action items:
- [ ] Provide a SVG for the Tracking Protection icon
- [ ] Try the addon in the "fast" branch and make a decision re: Issue #16 
- [ ] See if there's a usable clock icon and make a decision re: Issue #45

**Comment by biancadanforth** [comment]
### Final UX Review

Met in 2/28/18, jsavory found two bugs:
- [ ] #110 
- [ ] #111 

Met on 3/2, jsavory found one bug:
- [ ] #117 
Send her a XPI on Monday 3/5 morning to try things out before the demo Monday afternoon.

**Comment by biancadanforth** [comment]
Just checked with @jsavory with the latest, v1.0.3. and got a final UX sign-off.
